resources:
  - name: dbp_repo
    type: GitRepo
    configuration:
      gitProvider: Github                       # <-- replace with your integration
      path: tomjfrog/jfrog-pipelines-docker-sample    # <-- replace with your repository name
      branches:
        include: master

  - name: dbp_image
    type: Image
    configuration:
      registry: SaaS_tomjfrog                                # <-- replace with your artifactory integration
      sourceRepository: pipelines-quickstart-docker               # <-- required if registry is Artifactory
      imageName: tomjfrog.jfrog.io/pipelines-quickstart-docker/dbp  # < -- replace with your image path and name
      imageTag: latest
      autoPull: true
      
  - name: dbp_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: SaaS_tomjfrog
      buildName: dbp_build
      buildNumber: 1    

  - name: dbp_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: SaaS_tomjfrog
      buildName: dbp_build
      buildNumber: 1
      

pipelines:
  - name: Docker_Build_And_Push
    configuration:
      jfrogCliVersion: 2  
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: tomjfrog.jfrog.io/pipelines-quickstart-docker/dbp  # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: dbp_repo
          integrations:
            - name: SaaS_tomjfrog                            # <-- replace with your artifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: pipelines-quickstart-docker
          integrations:
            - name: SaaS_tomjfrog                            # <-- replace with your artifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: dbp_image

      - name: publish_dbp_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: dbp_build_info

      - name: promote_dbp_build
        type: PromoteBuild
        configuration:
          targetRepository: pipelines-quickstart-docker
          integrations:
            - name: SaaS_tomjfrog
          inputResources:
            - name: dbp_build_info
          outputResources:
            - name: dbp_promoted_build_info
